version: '3.8'
services:
  express:
    container_name: SEMINARIUM_BACKEND
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - BPMBLIMIT=10mb
      - LOGGERLVL=dev
      - JWTSECRET=mysecretphrase
      - JWTEXPIRE=1h
      - DBDIAL=postgres
      - DBNAME=seminarium
      - DBUSER=lolcat
      - DBPASS=lolcat
      - DBHOST=POSTGRES_DATABASE
      - DBLOGC=false
      - DBRESET=false
      - SALTLVL=10
    networks:
      - npm_default

  nextjs:
    container_name: SEMINARIUM_FRONTEND
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - APIURL=https://semiunarium.frenzoid.dev/api
    networks:
      - npm_default

networks:
  npm_default:
    external: true
