version: '3.8'
services:
  express:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./express:/app

  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    volumes:
      - ./nextjs:/app
